language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master
  - /^greenkeeper/.*$/

install:
  - npm install
  - npm run export

script:
  - npm run lint
  - echo "TODO tests"
