# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  command = "npm run export"
  functions = ".netlify/functions/"
  publish = "__sapper__/export"
[[redirects]]
#masstagger
/masstagger/*  https://masstagger.com/:splat  200
/api-pushshift/*  https://api.pushshift.io/:splat  200

#netlify
/*    /index.html   200
